[package]
name = "rust-slic"
version = "0.1.0"
authors = ["Alexandre Kirszenberg <alexandre.kirszenberg@epita.fr>"]
edition = "2018"

[dependencies]
image = "0.22.3"
glam = "0.8.0"
lazy_static = "1.4.0"
palette = "0.4.1"
structopt = { version = "0.3", default-features = false }
